### PR TITLE
feat: Update aws-nuke

### PR DESCRIPTION
**Pull request by rwhelan**
## Proposed changes

Update aws-nuke version.  Since https://github.com/Optum/aws-nuke/pull/6 got merged, this PR is to update the version of aws-nuke used by dce.  It would **require** the associated tag be created on Optum/aws-nuke.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (changes to code, which do not change application behavior)

## Checklist

- [x] I have filled out this PR template
- [x] I have read the [CONTRIBUTING](https://github.com/Optum/dce/blob/master/docs/CONTRIBUTING.md) doc
- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (`README.md`, inline comments, etc.)
- [x] I have updated the `CHANGELOG.md` under a `## next` release, with a short summary of my changes

## Relevant Links

https://github.com/Optum/aws-nuke/pull/6

## Further comments

The tag referenced in this PR would have to be created on the Optum/aws-nuke repo.

If getting this applied is better done via an issue, I can close the PR and create an issue.

### CODE REVIEW

**Comment by eschwartz** [comment]
Thanks @rwhelan !

**Comment by eschwartz** [comment]
Build is failing with:

> Formatting golang code... go: github.com/Optum/aws-nuke@v1.2.0: reading https://repo1.uhc.com/artifactory/api/go/golang-virtual/github.com/%21optum/aws-nuke/@v/v1.2.0.mod: 404 Not Found
make: *** [lint] Error 1

I'd thought we tagged that release, but I guess not. I'll look into it

**Comment by eschwartz** [comment]
Waiting on https://github.com/Optum/aws-nuke/pull/7

**Comment by eschwartz** [comment]
Released Optum/aws-nuke v1.2.0

**Comment by eschwartz** [comment]
@rwhelan sorry this has taken so long. I'm actually moving off the DCE team at Optum this week, so I want to pass this PR off @robologic to shepherd through.

@robologic can you take the ball on this one, please?

**Comment by jayanandagit** [comment]
Addressed. Closing.

**Pull request closed without merging**
