### PR TITLE
added tag:* to policy template

### PR DESCRIPTION
**Pull request by wrschneider**
Signed-off-by: Bill Schneider <bill.schneider@optum.com>

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (changes to code, which do not change application behavior)

## Checklist

- [x] I have filled out this PR template
- [x] I have read the [CONTRIBUTING](https://github.com/Optum/dce/blob/master/docs/CONTRIBUTING.md) doc
- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (`README.md`, inline comments, etc.)
- [x] I have updated the `CHANGELOG.md` under a `## next` release, with a short summary of my changes

### CODE REVIEW

**Comment by wrschneider** [comment]
> I'm in between requesting changes or saying this is good. @eschwartz we can just take that on as an extra thing I just don't want to lose it.
> 
> We should get tag:* added here too. https://github.com/Optum/dce/blob/master/docs/policies.md#organizations-and-service-control-policies-scps

Done

**Comment by wrschneider** [comment]
> I'm in between requesting changes or saying this is good. @eschwartz we can just take that on as an extra thing I just don't want to lose it.
> 
> We should get tag:* added here too. https://github.com/Optum/dce/blob/master/docs/policies.md#organizations-and-service-control-policies-scps

Done

**Comment by wrschneider** [comment]
> I'm in between requesting changes or saying this is good. @eschwartz we can just take that on as an extra thing I just don't want to lose it.
> 
> We should get tag:* added here too. https://github.com/Optum/dce/blob/master/docs/policies.md#organizations-and-service-control-policies-scps

Done

**Comment by marinatedpork** [comment]
The checks have indeed [all passed](https://dev.azure.com/OptumDCE/DCE/_build/results?buildId=2285&view=results) for this branch, but it seems Github and Azure DevOps are not syncing on this branch. I am going to go ahead as this PR is effectively ✅ .

**Pull request merged**
