### PR TITLE
Proposal for dependencies upgrade

### PR DESCRIPTION
**Pull request by hellgate75**
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (changes to code, which do not change application behavior)

## Checklist

- [x] I have filled out this PR template
- [ ] I have read the [CONTRIBUTING](https://github.com/Optum/dce/blob/master/docs/CONTRIBUTING.md) doc
- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (`README.md`, inline comments, etc.)
- [x] I have updated the `CHANGELOG.md` under a `## next` release, with a short summary of my changes

### CODE REVIEW

**Comment by pkn4645** [comment]
@jayanandagit  - successful execution of the CLA is required **before** merging a PR into an Optum project - it is not optional - please ensure that the PR submitter signs the CLA asap (FYI @amyschoen )

**Comment by amyschoen** [comment]
@hellgate75, I had to revert this PR since you didn't sign the CLA before our team merged it in.  Please submit this change again and make sure to sign the CLA.

@jayanandagit, this is a warning.  If you ignore the CLA again and merge in another change without it signed, I will need to remove your admin access and institute my own branch protections on your repo.

**Comment by hellgate75** [comment]
I signed the CLA and @jayanandagit signed out the CLA too. Can you please help us to complete our tasks and keep to keep merged this change with the original branch? Thanks

**Comment by amyschoen** [comment]
It looks like ftorelli made the actual commits.  See the comments from CLA assistant :point_up: @hellgate75.  That user is going to need to sign the CLA.

**Pull request merged**
