### PR TITLE
Fix/broken doc links

### PR DESCRIPTION
**Pull request by nathanagood**
## Proposed changes

Fixed issues with documentation by moving documentation over to Sphinx, which provides more capability.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (changes to code, which do not change application behavior)

## Checklist

- [x] I have filled out this PR template
- [x] I have read the [CONTRIBUTING](https://github.com/Optum/dce/blob/master/docs/CONTRIBUTING.md) doc
- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (`README.md`, inline comments, etc.)
- [ ] I have updated the `CHANGELOG.md` under a `## next` release, with a short summary of my changes

### CODE REVIEW

**Comment by marinatedpork** [comment]
@nathanagood just to clarify: a developer builds the swagger.json locally and commits if there is a change to swagger docs?

**Comment by nathanagood** [comment]
> @nathanagood just to clarify: a developer builds the swagger.json locally and commits if there is a change to swagger docs?

Yes, at least for now. :( I looked pretty hard but I could not find a parser that would use the YAML version.

**Pull request merged**
