### PR TITLE
added application-autoscaling:*

### PR DESCRIPTION
**Pull request by wrschneider**
## Proposed changes

Missing permission to application-autoscaling:*, needed to make autoscaling fully work

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (changes to code, which do not change application behavior)

## Checklist

- [x] I have filled out this PR template
- [x] I have read the [CONTRIBUTING](https://github.com/Optum/dce/blob/master/docs/CONTRIBUTING.md) doc
- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (`README.md`, inline comments, etc.)
- [x] I have updated the `CHANGELOG.md` under a `## next` release, with a short summary of my changes

### CODE REVIEW

**Comment by wrschneider** [comment]
> Looks good. There is an additional configuration file to which this should be added, as we use a tool periodically to generate this list (see the `tools` folder). I'll add that so these remain in sync.

Thanks.  BTW, I noticed there are no specific tasks in was-nuke to handle application-autoscaling.  Still, but it looks like application autoscaling targets/policies are similar to tags in that they disappear when the underlying resource is destroyed.

**Comment by AmudaPalani** [comment]
#run Optum.dce

**Pull request merged**
